### PR TITLE
Add linux aarch64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel support.
Related to #144. @indygreg Could you please review this PR?

### CODE REVIEW

**Comment by odidev** [comment]
@indygreg Could you please review this PR?

**Comment by odidev** [comment]
@indygreg Could you please have a look at this PR?

**Comment by odidev** [comment]
@indygreg Could you please review this PR?

**Review by indygreg — APPROVED** [review]
This looks good. I'll push this with some conflict fixups in the next few hours.

**Comment by indygreg** [comment]
This was committed as https://github.com/indygreg/python-zstandard/commit/f9bb88918a113a6dc3aa733045a79002a38a6a8c.

Thanks for the contribution!

**Pull request closed without merging**
