### PR TITLE
Upgraded zstd to 1.1.4

### PR DESCRIPTION
**Pull request by thedrow**
This version introduces performance improvements and two new API calls.

See https://github.com/facebook/zstd/releases/tag/v1.1.4

### CODE REVIEW

**Comment by thedrow** [comment]
Seems like there are adjustments that need to be done in order to support 1.1.4.
Can you help me interpret the test results?

**Comment by indygreg** [comment]
I have a local patch that also integrates zstd 1.14. And my test failures match what Travis and AppVeyor are showing.

The test failures for content size being 0 when non-0 was expected certainly look like an upstream regression.  Or we're not using the APIs correctly. Or upstream changed behavior on us. Either way, an issue against upstream should be filed.

The failure in `test_estimated_compression_context_size` just needs the expected value changed. Upstream changed the size and the test needs to reflect that.

I haven't tracked down the test failure in `test_read_large`. Again, it certainly looks like upstream changed behavior. It might be acceptable. It might not be. This one will require more digging.

I'm also not sure why `test_item_failure` is failing.

**Comment by thedrow** [comment]
I'll change the test assertion for `test_estimated_compression_context_size`. 
Is there anything else I can do that doesn't require research?

**Comment by indygreg** [comment]
Without research, I can't think of anything :/

**Comment by indygreg** [comment]
Upstream patched the issue with multi-threaded compression APIs not writing the content size. I cherry picked that locally and it makes our test failures go away.

The remaining issue with differing content in test_read_large is also due to buggy behavior with regards to content size writing. I've filed facebook/zstd#641.

**Comment by indygreg** [comment]
I resolved the remaining content size issue with upstream and pushed a commit that made the code compatible with 1.1.4 a few minute ago.

I also edited your commits slightly before incorporating them into the final history.

Thank you for the contribution.

**Pull request closed without merging**
