### PR TITLE
CI: Add Python 3.8

### PR DESCRIPTION
**Pull request by mhils**
This PR adds Python 3.8 to the CI builds. It would be great to have 3.8 wheels on PyPI! 😃

### CODE REVIEW

**Comment by indygreg** [comment]
Thank you for this PR.

It looks like CI failed. So this needs more work.

I'm pretty religious about pinning dependencies. I suspect I pinned a Docker image somewhere and the pinned image doesn't have Python 3.8 available.

**Comment by mhils** [comment]
Thanks for the super prompt reply. I fixed the manylinux builds (I believe, CI will tell) and removed Python 3.8 for Anaconda as conda-build doesn't seem to support it yet.

**Comment by mhils** [comment]
Is there any secret to using pip-compile? If I run 
```
pip-compile --generate-hashes --output-file=ci/requirements.txt ci/requirements.in
```
I get a requirements.txt with lots of dependencies missing. 😕

**Comment by indygreg** [comment]
I rebased this manually and landed as 41c38ef5ec02586cf3aaf91cfc18bb69a0efdef7. Thank you for the contribution!

As part of this, I discovered that the requirements.txt file needs to be generated with Python 2.7. Also, CI is failing on `master` due to zstd 1.4.4 upgrade. Hopefully I'll fix that soon.

**Comment by mhils** [comment]
Thanks so much @indygreg! :smiley:

**Pull request closed without merging**
