### PR TITLE
Allow c-extension to link with system zstd

### PR DESCRIPTION
**Pull request by terrelln**
* Required zstd patch e65aab8e0fa823d91a76490924d1d7a67b485aa2 to avoid
  including "mem.h". This means users won't be able to link with
  unmodified system zstd until the next zstd version is released.
  It also requires that `zstdmt_compress.h` is installed.
* Since the c-extension uses zstd's `pool.h` for threading, its source
  and dependencies are always included.

Tests:
```
# Install zstd-1.1.3 with patch and zstdmt_compress.h
cd ~/zstd
git checkout master
git apply e65aab8e0fa823d91a76490924d1d7a67b485aa2
make install MOREFLAGS=-DZSTD_MULTITHREAD
cp lib/compress/zstdmt_compress.h /usr/local/include
# Test with system and non-system zstd
cd ~/python-zstandard
rm -rf build/
python setup.py test --system-zstd
python3 setup.py test --system-zstd
rm -rf build/
python setup.py test
python3 setup.py test
```

### CODE REVIEW

**Comment by indygreg** [comment]
I'm pretty busy for the next few days and may not get around to merging this until next week. I glanced at it and it seems reasonable. I figured a distro packager would want this capablity eventually.

I do want to spend more time to consider the implications for linking against an "untrusted" library. See the section in the README about why we bundle and statically link. The existing code in `c-ext/zstd.c` that verifies `ZSTD_versionNumber()` /might/ be good enough.

Also, don't worry about that failing AppVeyor test. It started failing a few days ago for reasons unknown to me.

**Comment by terrelln** [comment]
There's no rush to merge this.

You may want to also check `ZSTD_VERSION_NUMBER` to sanity check the header for consistency, if you don't already. If you need more support upstream for this let us know (or if there are more bugs like the dependency on "mem.h" to use `ZSTD_WINDOWLOG_MAX`).

**Comment by indygreg** [comment]
I did the mem.h related backport on my own and cleaned up some code related to it. I also did some minor cleanup that introduced conflicts in your commit. I didn't want to burden you with a new PR, so I fixed the conflicts myself and landed this for you.

Regarding distro packages, I have some big API changes slated in the upcoming 0.9 release. I plan to make 0.9 backwards compatible with the 0.8 API then drop compatibility in 0.10 (or 1.0 - I haven't decided yet). So it might be best to wait until 0.9 before adding python-zstandard to any distros. But if the distros want to "provisionally" accept the package or something, I guess that's fine. I just want to avoid people being stuck on 0.8.

**Comment by pixelb** [comment]
Cool, I'll start the process I think with what's there, but will wait until 0.9 before releasing to fedora/centos
thanks!

**Pull request closed without merging**
