### PR TITLE
Use PyType_Spec to define types instead of PyTypeObject.

### PR DESCRIPTION
**Pull request by glandium**
This is a first step towards possibly using the stable ABI.

### CODE REVIEW

**Review by indygreg — COMMENTED** [review]
Thanks for contributing this. Given the size of the diff, I'm not sure when I'll get around to reviewing this. But it is a patch I'm tentatively interested in taking.

Regarding adoption of the stable ABI, I'm not opposed. But I thought we made use of unstable APIs (like maybe `_PyBytes_Resize()`?). Some of these might be necessary to achieve peak performance.

But out of principle I support converging onto the stable ABI where it doesn't introduce performance or other usability drawbacks.

**Comment by glandium** [comment]
Would it help if I split this change in pieces, one per type?

The only two things that (besides Py_buffer, which is in the stable API since 3.11) are not in the stable API are _PyBytes_Resize and Py_SET_SIZE. When I looked superficially, it seemed it might be possible to switch to bytearrays.

**Comment by indygreg** [comment]
> Would it help if I split this change in pieces, one per type?

Yes.

> The only two things that (besides Py_buffer, which is in the stable API since 3.11) are not in the stable API are _PyBytes_Resize and Py_SET_SIZE. When I looked superficially, it seemed it might be possible to switch to bytearrays.

In theory we could switch to `bytearray`. But I consider this an API change since it is a distinct type from `bytes`. I'll need to think about the implications. I want to say I support the backwards compatibility break - it's for a good cause.

I also recall there being issues in older versions of Python where `bytearray` wasn't exactly as interchangeable with `bytes` as it should be. My memory is fuzzy. Maybe it was only on versions of Python we no longer support? But I do recall wanting to use `bytearray` at some point and something discouraged me from doing it. Maybe I left a breadcrumb somewhere...

**Comment by indygreg** [comment]
I'm going to ship the next release with zstd 1.5.4 to get that out the door. Then I'm going to drop Python 3.6 support. Then I'll look at this PR. And possibly start chipping at moving to the stable API so we can ship fewer wheels.

**Review by indygreg — APPROVED** [review]
I cherry picked all these commits locally. Although I applied them out-of-order because I deferred the `tp_buffer` and version sniffing changes to the end because they were special and I didn't understand what was going on at first.

I do wonder why CPython didn't stabilize these at the same time as all the other slots. 🤷‍♂️ 

Will push to `main` once branch CI passes.

Thanks for this refactor! Greatly simplifies the definition of the C types!

**Pull request closed without merging**
