### PR TITLE
Fix memory leak in stream_reader seek, fixes #82

### LINKED ISSUE #82: Seeking leaks memory
Seeking on a zstandard stream reader causes the full file to be read into ram.

Minimal example:

```
$ head -c 500M /dev/urandom > test.dat
$ zstd test.dat
```

```python
import zstandard as zstd
import os
import psutil

p = psutil.Process(os.getpid())
path = 'test.dat.zst'

reader = zstd.ZstdDecompressor().stream_reader(open(path, 'rb'))

chunk = reader.read(1)
while chunk:
    # seek 100 MB forward
    reader.seek(100 * 1024**2, 1)
    print(p.memory_info()[0] / 1024**2)
    chunk = reader.read(1)
```

Result:

```
114.1171875
214.1484375
314.1796875
414.2109375
514.2421875
```

If one only reads, only the currently read data is in RAM:

```
import zstandard as zstd
import os
import psutil

p = psutil.Process(os.getpid())
path = 'test.dat.zst'

reader = zstd.ZstdDecompressor().stream_reader(open(path, 'rb'))

chunk = reader.read(1)
while chunk:
    # seek one MB forward
    reader.read(100 * 1024**2)
    print(p.memory_info()[0] / 1024**2)
    chunk = reader.read(1)
```
Result
```
14.28515625
14.2890625
14.2890625
14.2890625
14.2890625
```

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by MaxNoe** [comment]
@indygreg Can you explain what fails at the tests? It seems it trys to curl download something but what curl returns is not a zip file. 

Maybe add `--fail` to the curl call?

**Comment by MaxNoe** [comment]
After adding the curl option it's clear the download fails with a 404. @indygreg what is happening here?

**Comment by MaxNoe** [comment]
This bug is really bothering us, it would be great if this simple fix could be merged and a new release be made.

**Comment by indygreg** [comment]
The memory leak patch was committed to master and the 0.11 branch and 0.11.1 was tagged and released. I'll attend to the curl patch another day, as it isn't as important (and arguably not necessary). The commit message doesn't say why it is warranted. Is that commit even needed?

**Comment by MaxNoe** [comment]
The Error Message on Travis was very unclear. This improved it. These flags are generally considered best practice for curl.

**Pull request closed without merging**
