### PR TITLE
Started using fastcover instead of cover.

### PR DESCRIPTION
**Pull request by KOLANICH**
Cover is too slow to be usable anyhow. Updated zstd for this. Fixed the tests.

### CODE REVIEW

**Comment by indygreg** [comment]
I think I'm fine with this change.

But, changes to the vendored zstd library need to be isolated to their own commit and follow the conventions for other commits that updated zstd. Due to security/trust concerns, doing the zstd update is something I insist on doing myself. If you refactor this PR so your changes are isolated from the zstd library changes via separate commits, I can review the `python-zstandard` specific changes and rebase this PR on top of the upgraded zstd library commits when I get around to landing them.

**Comment by KOLANICH** [comment]
Just feel free to take my commit, update zstd yourself and commit using `--amend`. But big IMHO - we should just take the upstream zstd automatically, probably with some hashes verification and not to clutter this repo with zstd sources.

**Comment by KOLANICH** [comment]
Have you merged this?

**Comment by indygreg** [comment]
No. I renamed the `master` branch to `main` and deleted the `master` branch. Apparently GitHub closed all open PRs associated with the `master` branch. Please open a new PR.

**Pull request closed without merging**
